import appError from "../error/appError.js";

export interface LLMOptions {
	gemini: (apiKey: string, userPrompt: string) => Promise<string>;
	chatgpt: (apiKey: string, userPrompt: string) => Promise<string>;
}

const GEMINI_MODEL = "gemini-2.5-flash";
const OPENAI_MODEL = "gpt-4o-mini";

const COMMON_SYSTEM_PROMPT = `
You are an expert GitHub profile README generator.

General rules:
- Adhere closely to the user's instructions and provided data.
- Output ONLY Markdown.
- Do not wrap the response in code blocks.
- Do not explain what you are doing.
- Do not add unnecessary intro or outro text.
- Make the README feel personalized, not generic.
- Use only the information provided by the user.
- Do not invent fake achievements, companies, stats, projects, links, or badges.
- If some information is missing, gracefully skip that part instead of writing placeholders.
- Avoid overusing emojis. Use them only when they improve readability.
- Keep formatting clean and readable on GitHub.
- Prefer simple Markdown over complex HTML.
- Use HTML only when it improves layout, alignment, badges, or visual presentation.
- Make section titles attractive but not childish.
- Do not include broken links, fake badges, or unavailable images.
- Do not include sensitive personal information unless the user explicitly provided it.
- Do not mention that the content was generated by AI unless explicitly asked.
- Preserve valid Markdown syntax.
- Do not escape Markdown characters unnecessarily.
- Do not include duplicate sections.
- Keep the content concise but impactful.

Style guidelines:
- Use strong headings.
- Use bullet points where useful.
- Use tables only when they genuinely improve readability.
- Use badges when appropriate.
- Keep spacing consistent.
- Make the README suitable for recruiters, developers, and collaborators.
- Highlight skills, projects, achievements, and online presence clearly.
- Use ## headings unless the user asks otherwise. Avoid using # for the main title to keep it subtle.

GitHub compatibility:
- The output must render properly in a GitHub README.md file.
- Avoid scripts, iframes, unsupported CSS, or unsafe HTML.
- Avoid excessive inline styling.
- Do not use Markdown features unsupported by GitHub.

Quality requirements:
- Make the final result polished enough to be directly pushed to the user's GitHub profile README.
- The content should feel human-written, not robotic.
`;

export async function generateViaGemini(
	apiKey: string,
	userPrompt: string
): Promise<string> {
	const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`;

	const response = await fetch(url, {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
		},
		body: JSON.stringify({
			systemInstruction: {
				parts: [{ text: COMMON_SYSTEM_PROMPT }],
			},
			contents: [
				{
					role: "user",
					parts: [{ text: userPrompt }],
				},
			],
			generationConfig: {
				temperature: 0.7,
				maxOutputTokens: 5000,
			},
		}),
	});

	if (!response.ok) {
		const errorText = await response.text();
		throw new appError(
			response.status,
			`Gemini request failed: ${response.status} ${errorText}`
		);
	}

	const data = await response.json();

	const text = data?.candidates?.[0]?.content?.parts
		?.map((part: { text?: string }) => part.text)
		?.filter(Boolean)
		?.join("");

	if (!text) {
		throw new appError(500, "Gemini response missing text content.");
	}

	return text.trim();
}

export async function generateViaChatGPT(
	apiKey: string,
	userPrompt: string
): Promise<string> {
	const response = await fetch("https://api.openai.com/v1/chat/completions", {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			Authorization: `Bearer ${apiKey}`,
		},
		body: JSON.stringify({
			model: OPENAI_MODEL,
			messages: [
				{
					role: "system",
					content: COMMON_SYSTEM_PROMPT,
				},
				{
					role: "user",
					content: userPrompt,
				},
			],
			temperature: 0.7,
			max_tokens: 5000,
		}),
	});

	if (!response.ok) {
		const errorText = await response.text();
		throw new appError(
			response.status,
			`ChatGPT request failed: ${response.status} ${errorText}`
		);
	}

	const data = await response.json();

	const text = data?.choices?.[0]?.message?.content;

	if (!text) {
		throw new appError(500, "ChatGPT response missing text content.");
	}

	return text.trim();
}

export const LLMs: LLMOptions = {
	gemini: generateViaGemini,
	chatgpt: generateViaChatGPT,
};